### ISSUE TITLE
Taskwarrior to Reminder sync - not working

### ISSUE THREAD

**Issue by tr0njavolta** [blampe/taskwarrior-reminders#13]
Just set up taskwarrior-reminders today on a machine with `taskd`. While I am seeing data from Reminders to TW, I'm not seeing anything from TW to Reminders. Is a hook or path change needed here?

**Comment by 0Chan-smc** [comment]
Is this still not working?

**Comment by tr0njavolta** [comment]
I have removed this from my taskwarrior setup because I could not get it to work. I'll close this issue.
