### ISSUE TITLE
how do I uninstall this?

### ISSUE THREAD

**Issue by narudarurarasya** [blampe/taskwarrior-reminders#8]
Hello, is there any simple way to undo the sync with `Reminders` app? I want to uninstall this for now.

**Comment by narudarurarasya** [comment]
I think I found the solution.. `make uninstall`

**Comment by narudarurarasya** [comment]
but I guess you also had to [remove the entry from LaunchAgents](https://github.com/blampe/taskwarrior-reminders/blob/master/Makefile#L19) under `uninstall` section

**Comment by blampe** [comment]
Good catch, I'll add that to the uninstall step!
